package com.example.mp08_proyectouf1;

import java.util.ArrayList;
import java.util.List;

public class ListaJugadores {

    List<Jugador> jugadores = new ArrayList<>();

    interface Callback {
        void terminar(List<Jugador> jugadores);
    }

    ListaJugadores(){
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.mbappe, R.drawable.mbappe2,R.drawable.psg, R.color.azulMarino, "Kylian Mbáppe", "180 mill€", "500K", "PSG", "23", "Francia", "Delantero Centro", "7", "1,78m", "75 Kg", "27", "Goles", "6", "Asistencias", "73", "Precision de tiro", "40", "Regates con éxito", R.drawable.logo_league1, R.drawable.psg,R.drawable.marsella, "League Uber Eats", "PSG", "Marsella", "21 feb", "17:00", R.drawable.psg, R.drawable.francia, "PSG", "Francia",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.haaland, R.drawable.haaland2,R.drawable.manchester_city, R.color.azulMarino, "Erling Haaland", "170 mill€", "500K", "Manchester City", "22", "Noruega", "Delantero Centro", "9", "1,94m", "88 Kg", "32", "Goles", "4", "Asistencias", "62%", "Precisión de tiro", "75%", "Precisión de pase", R.drawable.logo_champions, R.drawable.leizpig,R.drawable.manchester_city, "Uefa Champions League", "RB Leizpig", "Manchester City", "21 feb", "21:00", R.drawable.manchester_city, R.drawable.noruega, "Manchester City", "Noruega",0));
        jugadores.add(new Jugador(R.drawable.fondo_real_madrid, R.drawable.vinicius, R.drawable.vinicius2,R.drawable.real_madrid, R.color.white, "Vinícius Jr", "120 mill€", "500K", "Real Madrid", "22", "Brasil", "Extremo Izquierdo", "20", "1,76m", "73 Kg", "18", "Goles", "9", "Asistencias", "66%", "Precision de tiro", "61", "Regates con éxito", R.drawable.logo_champions, R.drawable.liverpool,R.drawable.real_madrid, "Uefa Champions League", "Liverpool", "Real Madrid", "21 feb", "21:00", R.drawable.real_madrid, R.drawable.brasil, "Real Madrid", "Brasil",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.bellingham, R.drawable.bellingham2,R.drawable.dormundt, R.color.azulMarino, "Jude Bellingham", "110 mill€", "120K", "Borussia Dormundt", "19", "Inglaterra", "Mediocentro", "22", "1,86m", "75 Kg", "10", "Goles", "6", "Asistencias", "1492", "Toques", "82%", "Precision de pases", R.drawable.logo_bundesliga, R.drawable.dormundt,R.drawable.hoffenheim, "Bundesliga", "Borussia Dormundt", "TSG Hoffenheim", "26 feb", "21:00", R.drawable.dormundt, R.drawable.inglaterra, "Borussia Dormundt", "Inglaterra",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.foden, R.drawable.foden2,R.drawable.manchester_city, R.color.azulMarino, "Phil Foden", "110 mill€", "172K", "Manchester City", "22", "Inglaterra", "Medio Ofensivo", "47", "1,71m", "70 Kg", "7", "Goles", "6", "Asistencias", "85%", "Precisión de pases", "918", "Toques", R.drawable.logo_champions, R.drawable.leizpig,R.drawable.manchester_city, "Uefa Champions League", "RB Leizpig", "Manchester City", "21 feb", "21:00", R.drawable.manchester_city, R.drawable.inglaterra, "Manchester City", "Inglaterra",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.pedri, R.drawable.pedri2,R.drawable.barcelona, R.color.azulMarino, "Pedri", "100 mill€", "239K", "Fc \nBarcelona", "20", "España", "Mediocentro", "8", "1,74m", "60 Kg", "7", "Goles", "1136", "Pases Totales", "89%", "Precisión de pases", "64%", "Precisión de tiro", R.drawable.logo_europa_league, R.drawable.manchester_united,R.drawable.barcelona, "Europa League", "Manchester United", "Fc Barcelona", "23 feb", "21:00", R.drawable.barcelona, R.drawable.espana, "Fc Barcelona", "España",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.musiala, R.drawable.musiala2,R.drawable.bayern, R.color.azulMarino, "Jamal Musiala", "100 mill€", "101K", "Bayern Munich", "19", "Alemania", "Medio Ofensivo", "42", "1,80m", "68 Kg", "14", "Goles", "10", "Asistencias", "71%", "Precisión de tiro", "84", "Precisión de pase", R.drawable.logo_bundesliga, R.drawable.bayern,R.drawable.union_berlin, "Bundesliga", "Bayern de Munich", "Union Berlin", "26 feb", "17:30", R.drawable.bayern, R.drawable.alemania, "Bayern de Munich", "Alemania",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.saka, R.drawable.saka2,R.drawable.arsenal, R.color.azulMarino, "Bukayo Saka", "100 mill€", "172K", "Arsenal", "21", "Inglaterra", "Medio Derecho", "7", "1,78m", "72 Kg", "10", "Goles", "8", "Asistencias", "82%", "Precisión de pases", "19%", "Entradas con éxito", R.drawable.logo_premier, R.drawable.arsenal,R.drawable.leicester, "Premier League", "Arsenal", "Leicester City", "25 feb", "16:00", R.drawable.arsenal, R.drawable.inglaterra, "Arsenal", "Inglaterra",0));
        jugadores.add(new Jugador(R.drawable.fondo_real_madrid, R.drawable.valverde, R.drawable.valverde2,R.drawable.real_madrid, R.color.white, "Fede Valverde", "100 mill€", "114K", "Real Madrid", "24", "Uruguay", "Mediocentro", "15", "1,82m", "78 Kg", "12", "Goles", "5", "Asistencias", "89%", "Precisión de pases", "59", "Duelos Ganados", R.drawable.logo_champions, R.drawable.liverpool,R.drawable.real_madrid, "Uefa Champions League", "Liverpool", "Real Madrid", "21 feb", "21:00", R.drawable.real_madrid, R.drawable.uruguay, "Real Madrid", "Uruguay",0));
        jugadores.add(new Jugador(R.drawable.fondo_real_madrid, R.drawable.tchouameni, R.drawable.tchouameni2,R.drawable.real_madrid, R.color.white, "Aurelién Tchouameni", "90 mill€", "34K", "Real Madrid", "23", "Francia", "Medio Defensivo", "18", "1,87m", "81 Kg", "94%", "Precisión de pases", "2", "Asistencias", "26", "Intercepciones", "85", "Duelos Ganados", R.drawable.logo_champions, R.drawable.liverpool,R.drawable.real_madrid, "Uefa Champions League", "Liverpool", "Real Madrid", "21 feb", "21:00", R.drawable.real_madrid, R.drawable.francia, "Real Madrid", "Francia",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.gavi, R.drawable.gavi2,R.drawable.barcelona, R.color.azulMarino, "Gavi", "90 mill€", "194K", "Fc \nBarcelona", "18", "España", "Medio", "30", "1,73m", "70 Kg", "18", "Entradas con éxito", "98", "Duelos Ganados", "89%", "Precisión de pases", "958", "Toques", R.drawable.logo_europa_league, R.drawable.manchester_united,R.drawable.barcelona, "Europa League", "Manchester United", "Fc Barcelona", "23 feb", "21:00", R.drawable.barcelona, R.drawable.espana, "Fc Barcelona", "España",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.kane, R.drawable.kane2,R.drawable.tottenham, R.color.azulMarino, "Harry Kane", "90 mill€", "183K", "Tottenham Hotspur", "29", "Inglaterra", "Delantero Centro", "10", "1,88m", "86 Kg", "19", "Goles", "7", "Asistencias", "64%", "Precisión de tiro", "72%", "Precisión de pase", R.drawable.logo_premier, R.drawable.tottenham,R.drawable.cheelsea, "Premier League", "Tottenham Hotspur", "Cheelsea", "26 feb", "14:30", R.drawable.tottenham, R.drawable.inglaterra, "Tottenham Hotspur", "Inglaterra",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.leao, R.drawable.leao2,R.drawable.milan, R.color.azulMarino, "Rafael Leao", "85 mill€", "89K", "Milán", "23", "Portugal", "Ataque", "17", "1,88m", "81 Kg", "9", "Goles", "7", "Asistencias", "75%", "Precisión de pases", "40", "Regates con éxito", R.drawable.logo_serie_a, R.drawable.milan,R.drawable.atalanta, "Serie A", "Milán", "Atalanta", "26 feb", "20:45", R.drawable.milan, R.drawable.portugal, "Milán", "Portugal",0));
        jugadores.add(new Jugador(R.drawable.fondo_real_madrid, R.drawable.rodrygo, R.drawable.rodrygo2,R.drawable.real_madrid, R.color.white, "Rodrygo Goes", "80 mill€", "172K", "Real Madrid", "22", "Brasil", "Extremo/Mediapunta", "21", "1,74m", "64 Kg", "10", "Goles", "7", "Asistencias", "90%", "Precisión de pases", "35", "Regates con éxito", R.drawable.logo_champions, R.drawable.liverpool,R.drawable.real_madrid, "Uefa Champions League", "Liverpool", "Real Madrid", "21 feb", "21:00", R.drawable.real_madrid, R.drawable.brasil, "Real Madrid", "Brasil",0));
        jugadores.add(new Jugador(R.drawable.fondo2, R.drawable.rice, R.drawable.rice2,R.drawable.west_ham, R.color.azulMarino, "Declan Rice", "80 mill€", "172K", "West Ham United", "24", "Inglaterra", "Medio Defensivo", "41", "1,85m", "84 Kg", "21", "Entradas con éxito", "105", "Duelos Ganados", "89%", "Precisión de pases", "1371", "Pases Totales", R.drawable.logo_premier, R.drawable.west_ham,R.drawable.nottingham_forest, "Premier League", "West Ham United", "Nottingham Forest", "25 feb", "16:00", R.drawable.west_ham, R.drawable.inglaterra, "West Ham United", "Inglaterra",0));
    }

    List<Jugador> obtener() {
        return jugadores;
    }

    void actualizar(Jugador jugador, float valoracion, Callback callback) {
        callback.terminar(jugadores);
    }

}
